### PR TITLE
More changes

### PR DESCRIPTION
**Pull request by unknowndomain**

### CODE REVIEW

**Comment by unknowndomain** [comment]
This adds a profile app for us to start building from.

**Comment by unknowndomain** [comment]
@mattp I was thinking maybe the various app plugins should be modified more like you had them originally so you can pass the database object into them from them?

**Comment by unknowndomain** [comment]
Also we need to deal with this `ensureAuthenticated` function that will end up everywhere. I know how you love to think of ways to abstract things.

**Comment by mattp** [comment]
Hi,

Sorry I don't think I'm the mattp you're looking for. Cheers.

**Pull request merged**
